### ISSUE TITLE
Docker image 4-4.0.2 stopped working  

### ISSUE THREAD

**Issue by hanc2006** [linuxserver/docker-code-server#102]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Current Behavior
The last published docker image has stopped working (**linuxserver/code-server:amd64-4.0.2**). The preview version **linuxserver/code-server:amd64-v4.0.2-ls111** works fine.

## Steps to Reproduce
1. Create a new Docker container with the latest image version 4.0.2
2. Open the browser on http endpoint

<img src="https://user-images.githubusercontent.com/4517251/154854052-0348192c-c057-4644-be07-f75f1c408c61.png" width="400" />

## Command used to create docker container (run/create/compose/screenshot)
docker run -d \
  --name=code-server \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Zurich \
  -p 8443:8443 \
  -v /path/to/appdata/config:/config \
  --restart unless-stopped \
  **linuxserver/code-server:amd64-4.0.2**

## Docker logs
The Docker log displays no apparent issue.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
setting permissions::configuration
setting permissions::workspace
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-02-20T16:54:08.698Z] info  code-server 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd
[2022-02-20T16:54:08.700Z] info  Using user-data-dir ~/data
[2022-02-20T16:54:08.742Z] info  Using config file ~/.config/code-server/config.yaml
[2022-02-20T16:54:08.742Z] info  HTTP server listening on http://0.0.0.0:8443/ 
[2022-02-20T16:54:08.742Z] info    - Authentication is enabled
[2022-02-20T16:54:08.742Z] info      - Using password from $PASSWORD
[2022-02-20T16:54:08.742Z] info    - Not serving HTTPS 
[17:54:12] Extension host agent started.
```

**Comment by skrenes** [comment]
I'm having the exact same issue. I went ahead and made a new container with a completely empty config folder and verified that it works with `4.0.1` but not `4.0.2`.

**Comment by gatesry** [comment]
> I'm having the exact same issue. I went ahead and made a new container with a completely empty config folder and verified that it works with `4.0.1` but not `4.0.2`.
> 
> Edit: just tested `v4.0.2-ls111` and it's also working. It's only the `latest`/`v4.0.2-ls112` that is showing the `404` error.

Confirming v4.0.2-ls110 is working as well. latest also produced 404.

**Comment by aptalca** [comment]
Unfortunately nothing in the build or runtimr logs jump out especially when compared to the previous working build. It might be an update to an npm package that caused it but there are way too many npm modules here and I don't have time to compare and dig into it at the moment.

Also unfortunate, coincidentally the upstream binaries (deb) don't work on armhf and aarch64 on 4.0.2 so switching to those is not an option.

For now, stay on the tag `v4.0.2-ls111` as it is the latest version and we'll switch to the upstream binaries with the next version to prevent npm issues.

**Comment by skrenes** [comment]
Thank you @aptalca 
Do you think it's worth filing this bug with the code-server repo? I haven't tested their docker image, but it looks like they're using a version at least as old as `v4.0.2-ls111`, so its probably better for us to wait until they're on a newer version. In any case, I thought you'd have a much more informed opinion.

**Comment by aptalca** [comment]
4.0.2 is the latest version. This new docker build was only updating os packages but somehow the npm install no longer produces a working build.

You can report it upstream but I doubt they'll do anything because they are currently aware that the deb packages they publish are broken but they are recommending using 4.0.1 until the next version is released.
