### ISSUE TITLE
linuxserver/code-server:latest = Yarn and npm  command not found!

### ISSUE THREAD

**Issue by M4TH76** [linuxserver/docker-code-server#104]
execute "yarn" in code-server terminal
------------------------------

## Expected Behavior
yarn install v1.22.17 ....

## Current Behavior
yarn command not found

## Steps to Reproduce
install/update to latest linuxserver/code-server
open terminal
run yarn

## Environment
**OS:** Unraid
**CPU architecture:** x86_64
**How docker service was installed:**
Unraid App

**Comment by M4TH76** [comment]
I've resolved this issue by downgrading to linuxserver/code-server:v4.0.2-ls111

**Comment by aptalca** [comment]
There is no more yarn or npm by default as we no longer install code-server via yarn

You can install them as mods if needed
