### ISSUE TITLE
How to make an internal api-call using REST ?

### ISSUE THREAD

**Issue by burton666** [linuxserver/docker-code-server#106]
If I add a port to the container and start a simple node express server I can access it using rest from outside by using postman with GET http://192.168.0.5:3002/api/persons . 

But when I try to use the vscode rest-client addon from inside the container and use "GET http://localhost:3002/api/persons" I get no response. What am I missing

**Comment by burton666** [comment]
I just realized that the rest-calls get sent correctly it is just the vscode rest-client that is bugged. After I send a rest request I get a blank tab opens that should show the result but nothing shows. But If I save the request all info appears in the saved file.

**Comment by aptalca** [comment]
code-server container does not have a web browser
