### ISSUE TITLE
Unable to launch a Python script

### ISSUE THREAD

**Issue by tonio6797** [linuxserver/docker-code-server#108]
Hello,
This is my first issue on GitHub.
Recently, I installed code-server on my NAS Synology DS220+ (DSM 7) via Docker, and I want to use it with Python.
So, I also installed Python extension. But immediately I got this message "Couldn't start client Python Tools".
When I want to run a py file, the terminal opens, and say : `bash: python: command not found`
In the preferences, I can select a python interpreter, but I don't know how to do it.
Could you help me please?

Thank you in advance, Best Regards,

**Comment by aptalca** [comment]
Did you install the python mod?

**Comment by tonio6797** [comment]
What is the difference between the extension and the module?

**Comment by Roxedus** [comment]
The mod installs python on your instance, the extension only gives you the tools to work with python in code-server

**Comment by tonio6797** [comment]
> The mod installs python on your instance, the extension only gives you the tools to work with python in code-server

Thank you for the answer.

> Did you install the python mod?

No, I thought it was included in the extension.
