### ISSUE TITLE
Installing a VS Code extension via Dockerfile fails

### ISSUE THREAD

**Issue by fabian-ro** [linuxserver/docker-code-server#109]
Hi,
I'm trying to create a custom container image using `linuxserver/code-server:4.3.0` as a base image.
My Dockerfile looks like this:

```
FROM linuxserver/code-server:4.3.0
RUN curl -Lo /config/vscode-bicep.vsix https://github.com/Azure/bicep/releases/download/v0.6.1/vscode-bicep.vsix
RUN /usr/local/bin/install-extension /config/vscode-bicepp.vsix
```

------------------------------

## Expected Behavior
The extension should be installed successfully.

## Current Behavior
Installation fails:
```
STEP 9/9: RUN /usr/local/bin/install-extension /config/vscode-bicepp.vsix
justc-envdir: fatal: unable to justc_envdir: No such file or directory
Error: error building at STEP "RUN install-extension /config/vscode-bicepp.vsix": error while running runtime: exit status 111
```

## Steps to Reproduce
1. Create a Dockerfile like above
2. Run `podman build -t code-server:0.1.0 .`

## Environment
**OS:** Windows Subsystem for Linux 2
**CPU architecture:** x86_64
podman version 3.4.2

**Comment by Roxedus** [comment]
[This](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) is the supported way to customize our containers.

The helper is using a function that only exists at runtime, as a part of the init, you would have to install it without the helper. 
Also keep in mind that the /config at buildtime by default is not the same /config at runtime.

**Comment by namnhcntt** [comment]
> Hi, I'm trying to create a custom container image using `linuxserver/code-server:4.3.0` as a base image. My Dockerfile looks like this:
> 
> ```
> FROM linuxserver/code-server:4.3.0
> RUN curl -Lo /config/vscode-bicep.vsix https://github.com/Azure/bicep/releases/download/v0.6.1/vscode-bicep.vsix
> RUN /usr/local/bin/install-extension /config/vscode-bicepp.vsix
> ```
> 
> ## Expected Behavior
> The extension should be installed successfully.
> 
> ## Current Behavior
> Installation fails:
> 
> ```
> STEP 9/9: RUN /usr/local/bin/install-extension /config/vscode-bicepp.vsix
> justc-envdir: fatal: unable to justc_envdir: No such file or directory
> Error: error building at STEP "RUN install-extension /config/vscode-bicepp.vsix": error while running runtime: exit status 111
> ```
> 
> ## Steps to Reproduce
> 1. Create a Dockerfile like above
> 2. Run `podman build -t code-server:0.1.0 .`
> 
> ## Environment
> **OS:** Windows Subsystem for Linux 2 **CPU architecture:** x86_64 podman version 3.4.2

Because container need to run /init before you can install extensions (before vscode is not init, so cannot install extensions).

For usecase, I have small tricky:
- Create a shellscript file (ex: vscode-extensions.sh) and fill your script install extensions:
```
sleep 20s # or more seconds if you want
/usr/local/bin/install-extension /tmp/vscode-extensions/alexiv.vscode-angular2-files-1.6.4.vsix
```
- Create a shellscript file (ex: starter.sh) with contents:
```
./vscode-extensions.sh & /init # this run in multithreading
```
- Create Dockerfile:
```
FROM lscr.io/linuxserver/code-server:4.2.0-ls117
ENTRYPOINT ["/starter.sh"]
```
- And build your customize image

**Comment by JcMinarro** [comment]
It didn't work to me.
Whenever the container is started, it runs the `/starter.sh` script but after some seconds the container is restarted.

I have fixed it by creating the install script and include it at `/etc/cont-init.d/` folder.
`99-vscode-extensions`
```
#!/bin/bash
echo "Installing 'Log File Highlighter' extension"
/usr/local/bin/install-extension emilast.LogFileHighlighter

echo "Installing 'Prettier - Code formatter' extension"
/usr/local/bin/install-extension esbenp.prettier-vscode

echo "Installing 'ESPHome' extension"
/usr/local/bin/install-extension ESPHome.esphome-vscode

echo "Installing 'Home Assistant Config Helper' extension"
/usr/local/bin/install-extension keesschollaart.vscode-home-assistant

echo "Installing 'Material Design Icons Intellisense' extension"
/usr/local/bin/install-extension lukas-tr.materialdesignicons-intellisense

echo "Installing 'UUID Generator' extension"
/usr/local/bin/install-extension netcorext.uuid-generator

echo "Installing 'indent-rainbow' extension"
/usr/local/bin/install-extension oderwat.indent-rainbow

echo "Installing 'YAML' extension"
/usr/local/bin/install-extension redhat.vscode-yaml

echo "Installing 'Error Lens' extension"
/usr/local/bin/install-extension usernamehw.errorlens
```

`Dockerfile`
```
FROM linuxserver/code-server:version-4.6.0

COPY 99-vscode-extensions /etc/cont-init.d/99-vscode-extensions
```
