### ISSUE TITLE
Default password for abc

### ISSUE THREAD

**Issue by WombleWoo7547** [linuxserver/docker-code-server#113]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I cannot get the default password for the abc user so I can't use sudo

------------------------------

## Expected Behavior
Does not need password because none set

## Current Behavior
Asking for password that has never been inputted

## Steps to Reproduce
1. Install Docker
2. Create the container of code-server WITHOUT the environment variables
3. Open the website
4. Open the terminal and type sudo (ANYTHING)

## Environment
**OS:Raspberry Pi OS Lite (32-bit)**
**CPU architecture:** arm32/arm64
**How docker service was installed:** `sudo apt install docker.io -y`

## Command used to create docker container (run/create/compose/screenshot)
Portainer template from pi-hosted/pi-hosted github repo 

## Docker logs

The docker logs showed no errors

**Comment by aptalca** [comment]
There is no usable default password. You need to set it with the env vars
