### ISSUE TITLE
Trivy security vulnerabilities in linuxserver/code-server:4.5.0

### ISSUE THREAD

**Issue by prabushi** [linuxserver/docker-code-server#114]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

There shouldn't be any security vulnerabilities with critical or high severity.

## Current Behavior

There was a list of security vulnerabilities identified with the image using the Trivy scanner.

**Summary**
```
Node.js (node-pkg) - Total: 25 (UNKNOWN: 0, LOW: 5, MEDIUM: 4, HIGH: 13, CRITICAL: 3)

linuxserver/code-server:4.5.0 (ubuntu 20.04) - Total: 68 (UNKNOWN: 0, LOW: 44, MEDIUM: 24, HIGH: 0, CRITICAL: 0)
```
Please find the full report attached [here](https://github.com/linuxserver/docker-code-server/files/9045420/result.json.zip).

## Steps to Reproduce

1. Run the Trivy CLI scanner against the linuxserver/code-server:4.5.0 docker image.

## Environment
**OS:** N/A
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Command used to create docker container (run/create/compose/screenshot)

Trivy scanner was run using the following command.
` docker run --rm -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:latest image linuxserver/code-server:4.5.0 `

## Docker logs

[Full report](https://github.com/linuxserver/docker-code-server/files/9045420/result.json.zip)

**Comment by Roxedus** [comment]
Thanks for the report, this is however not something we can address, as these are all comming from packages outside of our controll. 

Please take a read of out [blog  post](https://www.linuxserver.io/blog/image-vulnerability-scanning-and-you) covering our position on these types of reports.

**Comment by prabushi** [comment]
> Thanks for the report, this is however not something we can address, as these are all comming from packages outside of our controll.
> 
> Please take a read of our [blog post](https://www.linuxserver.io/blog/image-vulnerability-scanning-and-you) covering our position on these types of reports.

@Roxedus Thank you for the quick response. Will try to reach out to embedded package owners. 

It would be a great help if you could point to the mentioned blog post in your GitHub repo's [security policy](https://github.com/linuxserver/docker-code-server/security/policy).
