### ISSUE TITLE
Hashed password documentation needs clarification

### ISSUE THREAD

**Issue by shoon** [linuxserver/docker-code-server#119]
## Expected Behavior
The documentation should show examples of a valid hashed password (and the SUDO hashed password) in docker-compose or other environment as it is not intuitive or documented elsewhere. The user needs to transform the hashed password string to have no quotes and needs to replace all single $ with a double. The linked documentation has a hashed password example of:

`"$argon2i$v=19$m=4096,t=3,p=1$wST5QhBgk2lu1ih4DMuxvg$LS1alrVdIWtvZHwnzCM1DUGg+5DTO3Dt1d5v9XtLws4"`

and the user must transform that to be a valid environment as follows:

`HASHED_PASSWORD=$$argon2i$$v=19$$m=4096,t=3,p=1$$wST5QhBgk2lu1ih4DMuxvg$$LS1alrVdIWtvZHwnzCM1DUGg+5DTO3Dt1d5v9XtLws4`

## Current Behavior
The documentation has a link that shows the user how to generate hashed passwords but does not show how to transform and include them in the docker environment. This leads to either a runtime exception because of the single '$' characters in the string or the user is unable to login because they used quotes on the environment line.

## Steps to Reproduce

1. User visits the documentation link in the "Hashed code-server password" section
2. User generates their hashed password using the steps documented in the aforementioned link
3. The user copies the hashed password (either directly from the command line or by adding quotes as seen in the example given) from step #2
4. The user attempts to start the docker environment and login
5. The user will either see an error on startup and/or will be unable to login with the password they hashed in step #2

**Comment by aptalca** [comment]
> and the user must transform that to be a valid environment as follows:

"transforming" has nothing to do with this container. It's compose/yaml specific, so it affects docker compose, but not docker cli. Any container created via docker compose, having a dollar sign in an environment variable would need escaping , otherwise docker compose will treat it as a variable and try to substitute.
https://docs.docker.com/compose/compose-file/#interpolation
