### ISSUE TITLE
Any chance of adding an ARM image for raspi?

### ISSUE THREAD

**Issue by bokugaoyori** [linuxserver/docker-code-server#12]
[It seems the master branch just released the updates to compile an ARM binary.](https://github.com/cdr/code-server/issues/35) Will you guys add an ARM docker image for raspi. anytime soon?

**Comment by ericlewis** [comment]
@aptalca knock knock, they have added the binaries for ARM64

**Comment by aptalca** [comment]
but no arm32. Unfortunately, the way our ci is set up is, we can either build x86_64 only, or multi-arch, which would be all three. It would take considerable effort to change that.

**Comment by aptalca** [comment]
@bokugaoyori @ericlewis fyi, this image is now multi-arch and support amd64, arm32v7 and arm64v8
