### ISSUE TITLE
issue with extensions

### ISSUE THREAD

**Issue by effatee** [linuxserver/docker-code-server#124]
Hi there, 
After a fresh install using your docker-compose file, I've been evaluating the solution to see if it can fit my use-case.
Have started to install a couple of extensions like python, jupyter notebooks, pdf previews, markdown preview...
I can't get ***any*** them to work at all, and am left with blank pages each time...

Could this be related to the lack of domain name and ssl certifictes ?
Or something else I've missed in the requirements ? (or in known limitations)
Any part of the settings needing activation for extensions to work ?

Thanks

**Comment by drizuid** [comment]
Please fill out the issue template if you expect help.
