### ISSUE TITLE
ssh is now missing

### ISSUE THREAD

**Issue by mikedodge04** [linuxserver/docker-code-server#127]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

ssh is no longer installed
```
/usr/bin$ whereis ssh
ssh:
```

**Comment by aptalca** [comment]
We never explicitly installed it but openssh-client came in as a dependency of another package on focal. On jammy however it no longer is a dep it seems. We'll add it. Thanks for the heads up.

**Comment by drizuid** [comment]
I see ssh in there? 

`docker run --rm   --name=cstst   -e PUID=1006   -e PGID=996   -e TZ=Europe/London   -p 9090:8443   -v /tmp/cs:/config   lscr.io/linuxserver/code-server:latest`
```
docker exec -it cstst ssh -V
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by aptalca** [comment]
well, it was me who did that lol
I added `--no-install-recommends` during the rebase and it turns out openssh-client was a recommended dep for git.

Reverting that to maintain parity with the older image
