### ISSUE TITLE
Custom scripts in code-server not being run 

### ISSUE THREAD

**Issue by Destom** [linuxserver/docker-code-server#130]
---
name: Bug report
about: Create a report to help us improve

---
[linuxserverurl]: https://fleet.linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Container customisation is not working as documented 
## Current Behavior

Volume for custom scripts is not being mounted it looks like the directyory does not exist 
## Steps to Reproduce
1. using the https://fleet.linuxserver.io/image?name=linuxserver/code-server server
2. custom scripts from https://docs.linuxserver.io/general/container-customization
   volumes:
   - /opt/docker/vs_code/config:/config
   - /opt/docker/vs_code/custom-scripts:/custom-cont-init.d:ro
 
[root@ranch custom-scripts]# ll
total 4.0K
drwxr-xr-x. 2 root root 28 Oct 12 09:23 .
drwxr-xr-x. 5 root root 59 Oct 12 08:55 ..
-rw-r--r--. 1 root root 76 Oct 12 09:01 install-python
[root@ranch custom-scripts]# pwd
/opt/docker/vs_code/custom-scripts

3. Looks like the path is not being mounted and there is no scripts found. I think this is because the underlying folder is not there on the container
 [custom-init] No custom files found, skipping...

## Environment
**OS:**CentOS Stream release 8
**CPU architecture:** x86_64
**How docker service was installed:**
 from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
  code-server:
   image: lscr.io/linuxserver/code-server:latest
   container_name: code-server
   environment:
   - PUID=1000
   - PGID=1000
   - TZ=Europe/London
   volumes:
   - /opt/docker/vs_code/config:/config
   - /opt/docker/vs_code/custom-scripts:/custom-cont-init.d:ro
   ports:
   - 8443:8443
   restart: unless-stopped

## Docker logs
│-------------------------------------
;5│          _         ()
D^│         | |  ___   _    __
[[│         | | / __| | |  /  \
1;│         | | \__ \ | | | () |
5D│         |_| |___/ |_|  \__/
  │
  │
  │Brought to you by linuxserver.io
  │-------------------------------------
  │
  │To support LSIO projects visit:
  │https://www.linuxserver.io/donate/
  │-------------------------------------
  │GID/UID
  │-------------------------------------
  │
  │User uid:    1000
  │User gid:    1000
  │-------------------------------------
  │
  │[custom-init] No custom files found, skipping...
  │starting with no password
  │[2022-10-12T16:26:26.746Z] info  code-server 4.7.1 77bbed48315a7cc275dc05a53d197197928f4b88
  │[2022-10-12T16:26:26.747Z] info  Using user-data-dir ~/data
  │[2022-10-12T16:26:26.759Z] info  Using config file ~/.config/code-server/config.yaml
  │[2022-10-12T16:26:26.759Z] info  HTTP server listening on http://0.0.0.0:8443/
  │[2022-10-12T16:26:26.759Z] info    - Authentication is disabled
  │[2022-10-12T16:26:26.759Z] info    - Not serving HTTPS
  │[ls.io-init] done.
  │[17:26:27] Extension host agent started.
  │[17:26:29] [10.0.0.108][7bb46da5][ManagementConnection] Unknown reconnection token (never seen).
  │[17:26:29] [10.0.0.108][9d090873][ExtensionHostConnection] Unknown reconnection token (never seen).
  │[17:26:33] [10.0.0.110][bca9afff][ManagementConnection] Unknown reconnection token (never seen).
  │[17:26:33] [10.0.0.110][552dc745][ExtensionHostConnection] Unknown reconnection token (never seen).
  │[17:26:36] [10.0.0.110][b08bee0b][ManagementConnection] New connection established.
  │[17:26:37] [10.0.0.110][4bfc29df][ExtensionHostConnection] New connection established.
  │[17:26:37] [10.0.0.110][4bfc29df][ExtensionHostConnection] <228> Launched Extension Host Process.
  │[root@ranch custom-scripts]# │[custom-init] No custom files found, skipping...q
  │-bash: │[custom-init]: command not found
  │[root@ranch custom-scripts]#
  │[root@ranch custom-scripts]#
  │[root@ranch custom-scripts]#
  │[root@ranch custom-scripts]#
  │[root@ranch custom-scripts]# ls
  │install-python
  │[root@ranch custom-scripts]# ll
  │total 4.0K
  │drwxr-xr-x. 2 root root 28 Oct 12 09:23 .
  │drwxr-xr-x. 5 root root 59 Oct 12 08:55 ..
  │-rw-r--r--. 1 root root 76 Oct 12 09:01 install-python
  │[root@ranch custom-scripts]# pwd
  │/opt/docker/vs_code/custom-scripts
  │[root@ranch custom-scripts]#

**Comment by Roxedus** [comment]
Which version do you have running? `docker inspect -f '{{ index .Config.Labels "build_version" }}' code-server`

**Comment by Destom** [comment]
I'm not at home at the moment so will check later but I did the pull about 15 minutes before raising the issue so I presume the latest

**Comment by Destom** [comment]
Linuxserver.io version:- 4.7.1-ls135 Build-date:- 2022-10-05T11:50:13-05:00

**Comment by Destom** [comment]
anyone?

**Comment by kuba-orlik** [comment]
Contrary to the docs, you have to mount the custom scripts at `/config/custom-cont-init.d:ro`, NOT at `/custom-cont-init.d:ro`

**Comment by Roxedus** [comment]
@kuba-orlik 
Atleast look at the correct code.
Jammy base: https://github.com/linuxserver/docker-baseimage-ubuntu/blob/22c03eb186b9f2ee1e5ec2854cfd80a2d5b5ea59/Dockerfile#L54
From mods repo: https://github.com/linuxserver/docker-mods/blob/137ba003001f4c32c5d2333d7d8c80f11bce6fc1/docker-mods.v3#L11
