### ISSUE TITLE
Capability to enable debug log

### ISSUE THREAD

**Issue by JeanRessouche** [linuxserver/docker-code-server#133]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Increasing the log verbosity with an environment variable (usefull with docker) or a config.yaml setting.
Today i have an error 400 on each call that i can't debug as the log returns absolutely nothing.

## Current Behavior
Poor log, not params to have more

**Comment by Roxedus** [comment]
Code-server reads the `LOG_LEVEL` environment variable.
