### ISSUE TITLE
Unable to open jupyter notebooks files (ipynb)

### ISSUE THREAD

**Issue by Marceau-h** [linuxserver/docker-code-server#134]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hi, 
When opening a notebook file, the content isn't displayed.

![Bug](https://user-images.githubusercontent.com/106751184/198157551-728edfc5-ec58-47e9-903c-e63cc9c15275.png)

And the little activity bar never stops. 
This only happens on the lsatest version (4.8.0)

------------------------------

## Expected Behavior

The notebook should open and jou would be able to write code and execute it

## Current Behavior

The file seems to load forever

## Steps to Reproduce

1. Run code-server (with or without the python mode)
2. Create or open a `.ipynb` file
3. Wait for it to open
4. Wait for it to open

## Environment
**OS:** Unraid 6.11.1
**CPU architecture:** x86_64
**How docker service was installed:** Unraid

I've tried several clients, none of them would work.
Behind my ngnix or locally with the ip adress, same behavior.

## Command used to create docker container (run/create/compose/screenshot)

```bash
docker run
  -d
  --name='code-server-1'
  --net='bridge'
  -e TZ=X
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME=X
  -e HOST_CONTAINERNAME="code-server-1"
  -e 'PASSWORD'=X
  -e 'SUDO_PASSWORD'=X
  -e 'DEFAULT_WORKSPACE'='/config/workspace'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8443]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/code-server-logo.png'
  -p '25545:8443/tcp'
  -v '/mnt/user/appdata/code-server-1':'/config':'rw' 'lscr.io/linuxserver/code-server'
89975cc12c7e0d8c39ac370b1be78a6bfcaf1a94da17b631f085e67449206a1a
```

## Docker logs

```bash
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

setting up sudo access
adding abc to sudoers
setting sudo password using SUDO_PASSWORD env var
New password: Retype new password: passwd: password updated successfully
[custom-init] No custom files found, skipping...
[2022-10-26T23:34:49.280Z] info  code-server 4.8.0 005fa87699b4b3c791bd97693400dd016a7ee315
[2022-10-26T23:34:49.281Z] info  Using user-data-dir ~/data
[2022-10-26T23:34:49.290Z] info  Using config file ~/.config/code-server/config.yaml
[2022-10-26T23:34:49.290Z] info  HTTP server listening on http://0.0.0.0:8443/ 
[2022-10-26T23:34:49.290Z] info    - Authentication is enabled
[2022-10-26T23:34:49.290Z] info      - Using password from $PASSWORD
[2022-10-26T23:34:49.290Z] info    - Not serving HTTPS 
[2022-10-26T23:34:49.291Z] info    - Proxying the following domain:
[2022-10-26T23:34:49.291Z] info      - *.code-server.my.domain
[ls.io-init] done.
[01:34:50] Extension host agent started.
[01:34:50] [ip_adress][9274304e][ManagementConnection] Unknown reconnection token (never seen).
```

**Comment by aptalca** [comment]
You probably need to install jupyter

**Comment by Marceau-h** [comment]
I don't think that's the issue, it was running fine before, and when i changed the image from `lastest` to `4.7.1` it immediately worked again.

**Comment by aptalca** [comment]
Then you should report it to code-server

**Comment by Marceau-h** [comment]
Ok I will, I just thought that as I'm using this image it was more appropriate to post it here.
Thanks.

**Comment by aptalca** [comment]
Right, and that's fine. It's just that we didn't change anything on our end between those two versions, only the code server version changed. If it was working before but not anymore, the issue has to be on their end or Microsoft's.
