### ISSUE TITLE
Nothing happens when i click the button "Turn on Edit Sessions..."

### ISSUE THREAD

**Issue by khaivu-mta** [linuxserver/docker-code-server#135]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Dialog box opens Let me sign in

## Implementation steps and results?
I want to login Github but nothing happens when I click the button "Enable Session Editing..."

![image](https://user-images.githubusercontent.com/44091521/198868505-416bf320-8513-467c-8066-d61468ff5701.png)

## Environment
**OS:** Ubuntu 18.04.6 LTS
**CPU architecture:** x86_64
**Docker image:** linuxserver/code-server:4.8.1 (latest)

**Comment by rursache** [comment]
having the same problem

**Comment by drizuid** [comment]
issue template not filled out.
