### ISSUE TITLE
Ability to connect to this container from a local vscode instance

### ISSUE THREAD

**Issue by BeGj** [linuxserver/docker-code-server#136]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Should be possible to connect to this container, similiar to how you connect to a remote ssh machine.

## Current Behavior
Not possible, you have to use the frontend vscode provided by the container (?)

## Alternatives Considered
N.A.

**Comment by Roxedus** [comment]
This is not in the scope of the upstream software.

**Comment by Sebulba46** [comment]
So basically there is no way i can use this container through desktop application?

**Comment by j0nnymoe** [comment]
It's not a function of code-server, so no.
