### ISSUE TITLE
[BUG] “Add to home” does not create a PWA

### ISSUE THREAD

**Issue by iloveicedgreentea** [linuxserver/docker-code-server#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In ipados/ios, the add to home button should create a PWA for vscode-server. This is essential because there is either a vscode or webkit bug that breaks scrolling with the magic keyboard trackpad in safari. It works in the PWA but the add to home button only adds a bookmark. I believe this has something to do with a manifest somewhere but I am far from an expert in this domain

### Expected Behavior

“Add to home” should add a PWA to the home screen

### Steps To Reproduce

Launch container
Navigate to web app in safari on ios or ipad
Click add to home

### Environment

```markdown
- OS: Unraid v6
- How docker service was installed: Unraid via app store, using official image from your repo
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
That needs to be reported to the app devs

**Comment by aptalca** [comment]
Our image does not touch anything related to the manifest or the serving of the files. It just runs the upstream code server package on Ubuntu.

You didn't even fill out the issue template so we can't really help you.

One thing you can try is to clear the browser cache.
