### ISSUE TITLE
[FEAT] Rust module for code-server

### ISSUE THREAD

**Issue by Trevo525** [linuxserver/docker-code-server#138]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would love to see a rust module so that we could use code-server as a rust dev environment.

### Reason for change

I was looking through the mods and I saw some for dotnet, golang,  java, and more languages. But, I would love to have this for rust. I have recently began learning Rust and would love to have a website to be my dev environment when I change computers.

### Proposed code change

I would like a new mod created for code-server to add Rust as an easy option. I looked at the dockerfile for dotnet and it looked quite complicated, but java didn't seem quite so bad. But, I am not sure how to make it myself. The [official rust docker image](https://hub.docker.com/_/rust/) is built from the image files [here](https://github.com/rust-lang/docker-rust).

**Comment by aptalca** [comment]
It looks like it's just a matter of installing `rust`/`cargo` from the repo. You can use the universal package installer mod for that

**Comment by Trevo525** [comment]
I am away from home so I can't test this currently. But, this is what I came up with in my docker-compose. I will add it here in case someone searches `rust` in the issues in the future. Thanks for your response @aptalca!

```
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=git|cargo
```
