### ISSUE TITLE
web server not initializing when deploying container

### ISSUE THREAD

**Issue by woreibi** [linuxserver/docker-code-server#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I deploy container in logs I see that Node is aborting.
code is straight forward so I'm not sure what is issue here. 

I tried this on different hosts with docker on them, same result.

### Expected Behavior

I should be able to browse using a browser to port that is forwarded but not able to.

### Steps To Reproduce

deploy stack using code below via portainer.

version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=Password01
      - SUDO_PASSWORD=SudoPassword
    volumes:
      - /home/someuser/containers/codeserver:/config
    ports:
      - 8443:8443
    restart: unless-stopped

### Environment

```markdown
Ubuntu 20.04
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=Password01
      - SUDO_PASSWORD=SudoPassword
    volumes:
      - /home/someuser/containers/codeserver:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```

### Container logs

```bash
/app/code-server/lib/node[843]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7f01c6dc3d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7f01c6dc3e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]
```

**Comment by Roxedus** [comment]
Post full logs

**Comment by woreibi** [comment]
This is what keep going in a cycle in logs:

/app/code-server/lib/node[195]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7fb030853d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7fb030853e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[209]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7ff83ae1fd90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7ff83ae1fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[223]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7f6d6245fd90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7f6d6245fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[237]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7f1f5229bd90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7f1f5229be40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[251]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7fd5cb290d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7fd5cb290e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[265]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7f1d50354d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7f1d50354e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[279]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7fd9c3fa2d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7fd9c3fa2e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[293]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7fc2e23c3d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7fc2e23c3e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[307]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7f540fb6bd90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7f540fb6be40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

/app/code-server/lib/node[321]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

 1: 0xb06730 node::Abort() [/app/code-server/lib/node]

 2: 0xb067ae  [/app/code-server/lib/node]

 3: 0xb756fe  [/app/code-server/lib/node]

 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]

 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]

 6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]

 7: 0x7f80a2690d90  [/lib/x86_64-linux-gnu/libc.so.6]

 8: 0x7f80a2690e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]

 9: 0xa4080c  [/app/code-server/lib/node]

**Comment by aptalca** [comment]
Full log means it includes the init steps. Recreate the container, and copy the logs shortly after

**Comment by notafunction** [comment]
Also running into this issue, here are full logs from init to node error loop.

```
Starting code_codeserver_1 ... done
Attaching to code_codeserver_1
codeserver_1  | [migrations] started
codeserver_1  | [migrations] no migrations found
codeserver_1  | usermod: no changes
codeserver_1  |
codeserver_1  | -------------------------------------
codeserver_1  |           _         ()
codeserver_1  |          | |  ___   _    __
codeserver_1  |          | | / __| | |  /  \
codeserver_1  |          | | \__ \ | | | () |
codeserver_1  |          |_| |___/ |_|  \__/
codeserver_1  |
codeserver_1  |
codeserver_1  | Brought to you by linuxserver.io
codeserver_1  | -------------------------------------
codeserver_1  |
codeserver_1  | To support LSIO projects visit:
codeserver_1  | https://www.linuxserver.io/donate/
codeserver_1  | -------------------------------------
codeserver_1  | GID/UID
codeserver_1  | -------------------------------------
codeserver_1  |
codeserver_1  | User uid:    1000
codeserver_1  | User gid:    1000
codeserver_1  | -------------------------------------
codeserver_1  |
codeserver_1  | setting up sudo access
codeserver_1  | setting sudo password using SUDO_PASSWORD env var
codeserver_1  | New password: Retype new password: passwd: password updated successfully
codeserver_1  | [custom-init] No custom files found, skipping...
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[133]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f7c26114d90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f7c26114e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[147]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f7be82e7d90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f7be82e7e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[161]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f8db707fd90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f8db707fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[175]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f5b83fffd90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f5b83fffe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[189]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7fa08c18fd90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7fa08c18fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
```

**Comment by woreibi** [comment]
Hi,

Update docker version to latest on your host then attempt to create container again.

For me that fixed issue.


Thank you,
Wissam

On Jan 26, 2023 9:38 PM, Matt Latham ***@***.***> wrote:

Also running into this issue, here are full logs from init to node error loop.

Starting code_codeserver_1 ... done
Attaching to code_codeserver_1
codeserver_1  | [migrations] started
codeserver_1  | [migrations] no migrations found
codeserver_1  | usermod: no changes
codeserver_1  |
codeserver_1  | -------------------------------------
codeserver_1  |           _         ()
codeserver_1  |          | |  ___   _    __
codeserver_1  |          | | / __| | |  /  \
codeserver_1  |          | | \__ \ | | | () |
codeserver_1  |          |_| |___/ |_|  \__/
codeserver_1  |
codeserver_1  |
codeserver_1  | Brought to you by linuxserver.io
codeserver_1  | -------------------------------------
codeserver_1  |
codeserver_1  | To support LSIO projects visit:
codeserver_1  | https://www.linuxserver.io/donate/
codeserver_1  | -------------------------------------
codeserver_1  | GID/UID
codeserver_1  | -------------------------------------
codeserver_1  |
codeserver_1  | User uid:    1000
codeserver_1  | User gid:    1000
codeserver_1  | -------------------------------------
codeserver_1  |
codeserver_1  | setting up sudo access
codeserver_1  | setting sudo password using SUDO_PASSWORD env var
codeserver_1  | New password: Retype new password: passwd: password updated successfully
codeserver_1  | [custom-init] No custom files found, skipping...
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[133]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f7c26114d90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f7c26114e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[147]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f7be82e7d90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f7be82e7e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[161]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f8db707fd90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f8db707fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[175]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7f5b83fffd90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7f5b83fffe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
codeserver_1  | starting with no password
codeserver_1  | /app/code-server/lib/node[189]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
codeserver_1  |  1: 0xb06730 node::Abort() [/app/code-server/lib/node]
codeserver_1  |  2: 0xb067ae  [/app/code-server/lib/node]
codeserver_1  |  3: 0xb756fe  [/app/code-server/lib/node]
codeserver_1  |  4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/app/code-server/lib/node]
codeserver_1  |  5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [/app/code-server/lib/node]
codeserver_1  |  6: 0xacd239 node::Start(int, char**) [/app/code-server/lib/node]
codeserver_1  |  7: 0x7fa08c18fd90  [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  8: 0x7fa08c18fe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
codeserver_1  |  9: 0xa4080c  [/app/code-server/lib/node]
