### ISSUE TITLE
cant install compilers from vscode

### ISSUE THREAD

**Issue by zerocoolMT** [linuxserver/docker-code-server#142]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

when adding extentions such as python etc you cant test the code can this be added to the docker compose file from your end

### Reason for change

any one can test the code on the server directly so there is no need to install a copy of the file localy

### Proposed code change

apt-get install -y \
    git \
    jq \
    libatomic1 \
    nano \
    net-tools \
    netcat \
    sudo && \
    python3 \
    python3-venv \
    python3-pip \

**Comment by zerocoolMT** [comment]
also can you expose ssh port aswell so that we can use python on local machine instead of using the web gui

**Comment by aptalca** [comment]
There are various mod for this container.

We won't do ssh as we don't believe it's necessary
