### ISSUE TITLE
[FEAT] Update to latest VSCode version?

### ISSUE THREAD

**Issue by xlorepdarkhelm** [linuxserver/docker-code-server#148]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

There are extensions I would love to have access to that need at least version 1.77 for VSCode to be used. Any possibility of this being able to be accomplished?

### Reason for change

Some extensions (for instance: CodeGPT) are unavailable in the current supported 1.74.x version of vscode that code-server uses, and it would be nice to be able to use up-to-date VScode features & extensions.

**Comment by aptalca** [comment]
We don't have control over the VSCode version in code-server. You'd need to report it to them.

Alternatively, you can look into our [openvscode-server](https://github.com/linuxserver/docker-openvscode-server) container, which follows the VSCode releases more closely.
