### ISSUE TITLE
[FEAT] Remove password login

### ISSUE THREAD

**Issue by 825i** [linuxserver/docker-code-server#154]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I am already using Github OAuth is my SSO for code-server. Is there a way to disable the additional request for a password from the container specifically?

### Reason for change

Use only one secure auth method instead of requiring two.

**Comment by thespad** [comment]
You should just be able to edit ~/.config/code-server/config.yaml and set `auth` to `none`

**Comment by Roxedus** [comment]
Not setting the var at all should also run it with "none" as auth

**Comment by BhautikChudasama** [comment]
You can use `/usr/bin/entrypoint.sh --bind-addr="0.0.0.0:8080" --auth none .`.
