### ISSUE TITLE
Extension not working properly (Live Server)

### ISSUE THREAD

**Issue by sant-sh** [linuxserver/docker-code-server#16]
First of all thank you for bringing this image for code-server.

For me live server is not working (i haven't tested other feature) which is working if I installed directly using the binaries.

Extension:
https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer 

Screenshot:
![image](https://user-images.githubusercontent.com/9120889/72687527-8be31d00-3b24-11ea-9d6f-1c5ab29cb2f5.png)

Please let me know if any doing any mistakes.

**Comment by CHBMB** [comment]
Would you mind completing the template for issues so we can adequately assess things.

**Comment by aptalca** [comment]
Code server extensions are hosted by code server as they cannot use the official MS marketplace due to licensing issues. You should report any extension related issue upstream to code server.

**Comment by sant-sh** [comment]
I was about to close this issue as same thing is happening with code-server so its not the issue with container. 
Anyway, thank you for your help.

**Comment by pest39** [comment]
I installed the live server extension from code-server marketplace, I am unable to load any site in live server. When I try and select the folder the html is located I get a Not Found error. I have my code-server running through swag reverse proxy with the correct settings (as far as I can tell). I also have HTML Preview installed but is unable to load any links I put in the HTML file.
