### ISSUE TITLE
use another marketplace

### ISSUE THREAD

**Issue by krodelabestiole** [linuxserver/docker-code-server#162]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I don't know how to choose another marketplace.
 
I've tried to follow [this documentation](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) for VSCodium.

So for a start I have set accordingly these env vars in my `docker-compose.yml` file :
- `VSCODE_GALLERY_SERVICE_URL`
- `VSCODE_GALLERY_ITEM_URL`
- `VSCODE_GALLERY_CACHE_URL`
- `VSCODE_GALLERY_CONTROL_URL`

any other custom var I pass can be echoed in VSCode terminal but not these ones. It seems they are reset, they return empty.

Then I've tried the other solution : to create a `product.json` file. I don't know where to put it though. I've tried the followings :
- `config/.config/VSCodium/product.json`
- `config/.config/code-server/product.json`
- `config/.config/confistore/product.json`
- and I've tried and convert it to YAML in `config/.config/code-server/config.yaml`

all with no success. 

 I could not find any related info on [coder's doc](https://coder.com/docs/v2/latest) either.

### Reason for change

I would like to install and automatically update extensions that [Open VSX](https://open-vsx.org) does not provide.

**Comment by j0nnymoe** [comment]
Vscodium is not the same as code-server. Read through the documentation here https://coder.com/ and see if it's possible.

**Comment by krodelabestiole** [comment]
thanks for your feedback.

I have searched through it but could not find any relevant info there (I've mentioned it at the end of my message).
I don't know at this stage if  the problem is related to coder or its docker implementation (since any env var shows up but these ones).
At first I mistakenly thought code-server was based on VSCodium, but I guess these vars seem to be used in the original VSCode code from microsoft.
