### ISSUE TITLE
[FEAT] Expose bind-addr, auth, password and cert as environment variables

### ISSUE THREAD

**Issue by csvke** [linuxserver/docker-code-server#169]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Expose bind-addr, auth, password and cert as environment variable

### Reason for change

Have such environment variables to avoid manually changing the` ~/.config/code-server/config.yaml` file as per [Tailscale’s configuration suggestion](https://tailscale.com/kb/1166/vscode-ipad#:~:text=Visual%20Studio%20Code%20has%20quickly,any%20device%2C%20including%20an%20iPad) so one can access code-server securely using tailscale.

**Comment by drilus** [comment]
This is a good idea
