### ISSUE TITLE
[FEAT] Tracking of User Logins

### ISSUE THREAD

**Issue by basrihsn** [linuxserver/docker-code-server#172]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I suggest adding a feature to track user login activities within code-server. This would involve creating a mechanism to log details of user logins, such as timestamps and user identifiers, and possibly track the duration of active sessions. This functionality could be presented through a log file accessible to the user or via an interface within code-server that displays this information.

### Reason for change

As a user managing my code-server instance, I find it essential to have visibility into my login history for security and auditing purposes. Being able to review login activities would help me ensure that there is no unauthorized access to my development environment. Additionally, it would allow me to monitor my usage patterns, which could be beneficial for optimizing my workflow and managing resources more effectively. Also, I can see more clearly who is actively using it and who is not.

### Proposed code change

No, I don't.

**Comment by Roxedus** [comment]
If you have authorization handled at your reverse proxy, it would hold these logs. 
For any feature request to the application, file those to [coder/code-server](https://github.com/coder/code-server)
