### ISSUE TITLE
[FEAT] Preinstall packages from docker-compose

### ISSUE THREAD

**Issue by phyesix** [linuxserver/docker-code-server#174]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I am a front-end developer.

During development, I need packages like nodejs. I use Docker Watchtower and it updates automatically. Therefore, I have to reinstall the above packages every time. 

Is there a specific setting in the docker-compose file to pre-install the things I want it to install? 

### Reason for change

Developers in different areas of work can create a ready-made environment by adding the packages they want.

### Proposed code change

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      ..............
      **- PACKAGES=nodejs**
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped

**Comment by j0nnymoe** [comment]
Check out our container mods https://mods.linuxserver.io/?mod=code-server
