### ISSUE TITLE
[FEAT] docker compose disable telemetry parameter

### ISSUE THREAD

**Issue by LECOQQ** [linuxserver/docker-code-server#182]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to have a docker compose parameter such as DISABLE_TELEMETRY, which would enable/disable telemetry accordingly.
Concretely, this parameter would just launch code-server with the --disable-telemetry flag (cf [this](https://coder.com/docs/code-server/FAQ#how-do-i-disable-telemetry)) or without.

### Reason for change

I found it lacking. Many parameters are to be thrown when launching code-server, and we can't throw them when launching it through docker compose. 
Docker compose and dockerization is amazing, and in doing so, we must stick w/ it. But we also have to be able to add the coder/code-server intended parameters to have the full experience.
Furthermore, privacy is important. I don't want to send telemetry to coder - even if they claim to not use them against users, what's the goal of self-hosting if not for controling our digital life? :)

### Proposed code change

No - totally noob @docker compose programming, i'm a mere user but i'm willing to learn, and will try to do a PR shall i find the time to.

**Comment by Roxedus** [comment]
We hardcode this to disabled already. https://github.com/linuxserver/docker-code-server/blob/master/root/etc/s6-overlay/s6-rc.d/svc-code-server/run#L23

**Comment by LECOQQ** [comment]
I'm so bad. Sorry for the bother! Thx for the work :)
