### ISSUE TITLE
Can you please update the dockerfile to check the architecture?

### ISSUE THREAD

**Issue by camelator** [linuxserver/docker-code-server#21]
I am not a dockerfile specialist,
but I can see in the dockerfile line 23:
CODE_RELEASE=$(curl -sX GET "https://api.github.com/repos/cdr/code-server/releases/latest"
Having a look on this repo, I can see there are builds per architecture.
But in line 27:
select(.browser_download_url | contains("linux-x86_64"))
I am not sure what this part do, but it looks like it uploads the x86_64 architecture file.
This is why the final image does not work on my ARM64 board.
Instead I just replace the linux-x86_64 by linux-arm64 and the image works perfectly on my nano Fire3 board.
I don't know how to do that, but is it possible to check the architecture of the machine and download the relevant file?

Thanks and regards,

**Comment by aptalca** [comment]
This dockerfile is what we use to build the x86_64 image. You'd need to modify it yourself to build for other platforms

**Comment by aptalca** [comment]
@camelator this image is now multi-arch and supports amd64, arm32v7 and arm64v8
When you pull `linuxserver/code-server` it should get the right image for your arch

**Comment by camelator** [comment]
Well... Many thanks
I'll try it.
