### ISSUE TITLE
Dockerfile build error - cannot find version matching .4.1

### ISSUE THREAD

**Issue by ajurcevic** [linuxserver/docker-code-server#34]
## Expected Behavior
docker builds via dockerfile

## Current Behavior - output logs here
https://gist.github.com/ajurcevic/a54fa0c0e89ef7fa5906f8c2e62456b2

error line: 1198
error Couldn't find any versions for "code-server" that matches ".4.1"

## Steps to Reproduce
`git clone the repo`
`cd to folder`
`docker build --tag code:1.0 .`

## Environment
**OS:**   Debian 10    
**CPU architecture:** x86_64      
**How docker service was installed:**

**Comment by nemchik** [comment]
Can you try the build command from our readme?

https://github.com/linuxserver/docker-code-server#building-locally

```
docker build \
  --no-cache \
  --pull \
  -t linuxserver/code-server:latest .
```

**Comment by aptalca** [comment]
@ajurcevic see here: https://discourse.linuxserver.io/t/linuxserver-code-server-container-update-for-code-server-3-4-1/1734/2

It's an upstream issue and should be fixed with their next release

**Comment by aptalca** [comment]
However, you can pass a build arg to make it build the latest manually. Just pass the latest version with a "v" in the beginning

**Comment by ajurcevic** [comment]
Ahh thanks all 😊
