### ISSUE TITLE
Starting code-server container with userns-remap fails

### ISSUE THREAD

**Issue by thomasbley** [linuxserver/docker-code-server#42]
Since I'm using userns-remap in docker daemon,
I have to use userns=host to be able to write files inside a docker container with my host uid.
Starting code-server using userns=host fails.

## Expected Behavior
docker container starts

## Current Behavior
docker run --rm -it --userns=host linuxserver/code-server:latest bash
gives:
s6-overlay-preinit: fatal: unable to chown /var/run/s6: Operation not permitted

## Steps to Reproduce
/etc/docker/daemon.json
{"userns-remap": "dockremap", "icc": false,"experimental": true}
/etc/subuid
dockremap:231072:65536
/etc/subgid
dockremap:231072:65536

docker run --rm -it --userns=host linuxserver/code-server:latest bash
gives:
s6-overlay-preinit: fatal: unable to chown /var/run/s6: Operation not permitted

docker -v
Docker version 19.03.13, build 4484c46d9d

## Environment
**OS:Linux Mint 20
**CPU architecture: x86_64
**How docker service was installed:
ppa: https://download.docker.com/linux/ubuntu
dpkg --list | grep docker
ii  docker-ce                                     5:19.03.13~3-0~ubuntu-focal                         amd64        Docker: the open-source application container engine
ii  docker-ce-cli                                 5:19.03.13~3-0~ubuntu-focal                         amd64        Docker CLI: the open-source application container engine

docker -v
Docker version 19.03.13, build 4484c46d9d

## Command used to create docker container (run/create/compose/screenshot)
docker run --rm -it --userns=host linuxserver/code-server:latest bash

## Docker logs
s6-overlay-preinit: fatal: unable to chown /var/run/s6: Operation not permitted

Thanks for your help!

**Comment by Roxedus** [comment]
Know limitation with the S6-overlay. https://github.com/linuxserver/docker-unifi-controller/issues/62#issuecomment-726119049
