### ISSUE TITLE
Cant compile c code

### ISSUE THREAD

**Issue by dlgeraghty** [linuxserver/docker-code-server#45]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I guessed I would be able to write some code, c code for instance, and compile it

## Expected Behavior

Open a terminal in the IDE , execute ```gcc file.c```  and that should compile the file creating some output in the terminal

## Current Behavior

However, it throws an error, it says ```gcc: not found```

## Steps to Reproduce

1. Open a terminal tab inside the IDE and run ```gcc```
2. But then , if you execute : ```sudo docker exec -it code-server sudo apt update && sudo apt install -y gcc``` in your host os, it will tell you that gcc is already installed...thats what is confusing me the most

## Environment
**OS:** Raspbian 64 bits
**CPU architecture:** arm64
**How docker service was installed:**

the docker image was installed by the docker pull command in the docs

## Command used to create docker container (run/create/compose/screenshot)

I ran the docker container with the cli parameters, for testing

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2020-11-25T12:52:41.955Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2020-11-25T12:52:43.102Z] info  code-server 3.7.3 93fb76e4a71b1959ec2a23481ba2611200d714b2
[2020-11-25T12:52:43.112Z] info  Using user-data-dir ~/data
[2020-11-25T12:52:43.171Z] info  Using config file ~/.config/code-server/config.yaml
[2020-11-25T12:52:43.172Z] info  HTTP server listening on http://0.0.0.0:8443 
[2020-11-25T12:52:43.172Z] info    - Authentication is enabled
[2020-11-25T12:52:43.172Z] info      - Using password from $PASSWORD
[2020-11-25T12:52:43.172Z] info    - Not serving HTTPS
```

**Comment by aptalca** [comment]
The image itself does not have gcc, you have to install it.

I spun up a fresh container, installed gcc (apt update && apt install gcc), and then I can run it in code-server terminal:
```
abc@62ee7c85cb96:~/workspace$ gcc
gcc: fatal error: no input files
compilation terminated.
```

**Comment by dlgeraghty** [comment]
Oh! Thank you! I forgot to update the repository list with ```apt update```, noobie mistake...but I got it working now, what a great piece of software this one is!
