### ISSUE TITLE
Pressing enter in the VS Code IDE stops working

### ISSUE THREAD

**Issue by SegiH** [linuxserver/docker-code-server#53]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
After using code-server for a little while, when I press enter in the IDE, nothing happens. 

I expect that a new line would be inserted at the current cursor location

## Current Behavior
The cursor does not move to the beginning of the new next line as expected
I have to kill the npm process and reload the browser page to fix this issue and then restart npm again.

## Steps to Reproduce
1. Load code-server Docker container in a web page ( I use Firefox 85 on Windows 10 and Ubuntu)
2. After using it for a random period of time, pressing enter in VS Code stops working and nothing happens when you press enter. I have experienced this bug across multiple computers
3. Reload page in browser
4. Pressing enter inserts a new line again as expected.

## Environment
**OS:** Ubuntu Server 20.04
**CPU architecture:** x86_64
**How docker service was installed:** apt-get

## Command used to create docker container (run/create/compose/screenshot)
Compose Script: https://bpa.st/K23A

## Docker logs
Docker logs: https://bpa.st/EXQQ

**Comment by aptalca** [comment]
Either an issue with the reverse proxy or code server itself, in which case it should be reported upstream

**Comment by SegiH** [comment]
I do use a reverse proxy but I don't see how it could possibly be related. Seems like an issue with code server

**Comment by aptalca** [comment]
Then please report it upstream

**Comment by SegiH** [comment]
Where at exactly ? Can you please give me a link ?
