### ISSUE TITLE
Editing CSS script in Angular while dev server is running causes npm to crash due to auto saving in CS Vode

### ISSUE THREAD

**Issue by SegiH** [linuxserver/docker-code-server#54]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

VS Code in this code-server image appears to automatically save a file after a few seconds after a change has been made to the file without requiring you to hit save to save it. When I am editing a CSS file in an Angular project while the dev server is running (which you start by running npm start which runs the command ng serve --host 0.0.0.0 --proxy-config proxy.conf.json) if I have not typed out the css element name completely, the script is auto saved and throws a fatal error that can only be fixed by restarting npm. 

------------------------------

## Expected Behavior
When the CSS file is auto saved, it will reinterpret the CSS file with the new changes and the error will go away

## Current Behavior

The following error appears:

`Error: ./src/app/app.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(106:1) /config/code/You2Me/src/app/y2m/y2m.component.css Unknown word

  104 | }
  105 | 
> 106 | #test
      | ^

    at /config/code/You2Me/node_modules/webpack/lib/NormalModule.js:313:13
    at /config/code/You2Me/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /config/code/You2Me/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/config/code/You2Me/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /config/code/You2Me/node_modules/@ngtools/webpack/src/ivy/loader.js:57:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)` 

Fixing the CSS error does not cause this message to go away and npm has to be restarted

## Steps to Reproduce
1. Open a CSS Script while the Angular dev server is running.
2. For this example, say we want to add `#test { display: none; }`
3. Type #test at the bottom of the CSS script and wait until it auto saves
4. An error message like the one above appears
5. Fix this CSS block so that it reads `#test { display: none; }` and wait until it automatically saves the file
6. The fatal error does not go away like it does in a TypeScript file. npm has to be restarted

## Environment
**OS:**  Ubuntu Server 20.04
**CPU architecture:**  x86_64
**How docker service was installed:**
 apt-get

## Command used to create docker container (run/create/compose/screenshot)
Compose Script: https://bpa.st/K23A

## Docker logs
Docker logs: https://bpa.st/EXQQ

**Comment by aptalca** [comment]
Sounds like a code-server issue rather than a docker one and should be reported upstream

**Comment by SegiH** [comment]
> Sounds like a code-server issue rather than a docker one and should be reported upstream

Ok well I'm leaving this issue here if you guys want to do that
