### ISSUE TITLE
Support setting of fs.inotify.max_user_watches through environmental variable

### ISSUE THREAD

**Issue by poldim** [linuxserver/docker-code-server#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Provide ability to set `fs.inotify.max_user_watches` as environmental variable.  This seems to be triggered when you've got large directories.  For me this was happenning with Plex and Radarr which I imagine many users have.
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
------------------------------

## Desired Behavior
https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc/17437601#17437601 is an example of a solution which just increases the allowable `fs.inotify.max_user_watches=524288`

## Current Behavior
Currenty cannot run this command inside the container
```
root@aa152290bfc6:/# cat /proc/sys/fs/inotify/max_user_watches
8192
root@aa152290bfc6:/# echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
fs.inotify.max_user_watches=524288
sysctl: setting key "fs.inotify.max_user_watches": Read-only file system
sysctl: setting key "fs.inotify.max_user_watches": Read-only file system
root@aa152290bfc6:/# 
```

## Alternatives Considered
Setting individual folders to be ignored but this can be somewhat of a whackamole approach as you may always be adding more folders that are monitored by code.

**Comment by aptalca** [comment]
If you can't set it inside the container, neither can we. An env var is not gonna do anything.

With that said, I'm pretty sure you can set sysctls in your docker run or compose

**Comment by poldim** [comment]
I tried a few things per @aptalca's recommendsation for setting sysctls in my docker compose:

```
sysctls:
  - fs.inotify.max_user_watches=524288
```

```
command: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
```

```
command:
  - "/bin/sh"
  - "-c"
  - |
    set -o errexit
    set -o xtrace
    while sysctl -w fs.inotify.max_user_watches=525000
    do
      sleep 60s
    done
```
None of these worked.  Some googling shows that this value is read only from the host.  In my case, the docker Host (Synology NAS) needed to be updated.  This can walk you through it: https://howchoo.com/node/node-increase-file-watcher-system-limit
