### ISSUE TITLE
Upgrade base ubuntu image from 18.04 to the latest LTS (20.04 Focal)

### ISSUE THREAD

**Issue by sub20hz** [linuxserver/docker-code-server#62]
I couldn't find anything on a roadmap or discussion about it, but are there any plans to take the base Ubuntu image from 18.04 -> 20.04? 

This would be much appreciated, as I'm encountering more and more scenarios where the 18.04 repos are too out of date, or trying to install from external ppas assumes ubuntu dependencies only available on 20.04 or newer

Appreciate all the support you've all included for code-server so far, I've been absolutely addicted to using it

**Comment by aptalca** [comment]
We are slowly moving images over to focal, but there is one major issue affecting focal with arm32 devices: https://docs.linuxserver.io/faq#libseccomp
Therefore, unless there is an urgency, we tend to hold off on the upgrade.

I'll look into upgrading this, but we also need to make sure all the mods are compatible first.

**Comment by vital987** [comment]
Have a look at my [project](https://github.com/vital987/code-server).

**Comment by sandroLuk** [comment]
Hi, is there a upgrade of this issue? I'm also interessted in focal support because of the newer python version (3.8) in the focal repos. Best regards and keep up the good work!

**Comment by sandroLuk** [comment]
Hi, i have to ask again. The python-version problem still persists. As far as i understand, the libseccomp2 bug affects only 32 bit distros and that's why an update to a focal base-image can't be done? I guess that's a very small percentage of distros using the codeserver image. So wouldn't it be an option to make a fork for 32 bit and update the mainline?

**Comment by Roxedus** [comment]
libseccomp is not really a problem anymore, it's currently about trying to make sure most of the mods work with a rebase. So far testing seems good

**Comment by Nimrod-666** [comment]
Hi @aptalca @LinuxServer-CI  i've seen that @Roxedus requested a pull request for this issue which is stale for a while now. ( https://github.com/linuxserver/docker-code-server/pull/75 )
Is there a reason why it's not getting merged?

**Comment by Roxedus** [comment]
Real life.

**Comment by sandroLuk** [comment]
Classic :D No offense, just was curious if it has been forgotten something. But very cool that it's still on the list, looking forward for that feature! Thanks!

**Comment by j0nnymoe** [comment]
You're more than welcome to test the PR aswell to see if you stumble upon any issues.

**Comment by sandroLuk** [comment]
You're right. I'll have a look!
