### ISSUE TITLE
Alpine image

### ISSUE THREAD

**Issue by parsalotfy** [linuxserver/docker-code-server#66]
Hi, Could you please add an image running on Alpine instead of Ubuntu?
Alpine is more lightweight.
Thank you for your efforts

**Comment by aptalca** [comment]
No plans for that. All its mods are ubuntu based and let's face it, ubuntu/debian is a much more popular dev environment than alpine

**Comment by parsalotfy** [comment]
Ok, it seems that we should accept that :))
Thank you for answering
