### ISSUE TITLE
python.execInTerminal-icon' not found

### ISSUE THREAD

**Issue by capriciousduck** [linuxserver/docker-code-server#67]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
After creating a python file, the python interpreter extension should be activated.
## Current Behavior

Even after installing the python extension, the interpreter doesn't show up. I get the following error upon clicking on the run button 
`command 'python.execInTerminal-icon' not found`

## Steps to Reproduce

I used the following docker command.

`
docker run -d --restart unless-stopped \
  --name=vscode \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Europe/London \
  -e PASSWORD=vscode \
  -p 8443:8443 \
  -v /mnt/mclaren/vscode:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/code-server
`

**Comment by Roxedus** [comment]
This is not a container issue, its more or less due to how the code-server pipeline works. The python extension usually gets updated to work with the latest version of vscode, and code-server lags a bit behind. This is well documented upstream. <https://github.com/cdr/code-server/issues?q=python+extension>

**Comment by capriciousduck** [comment]
What do I do now to fix it?

**Comment by Roxedus** [comment]
The top issue from that link sheds some light: <https://github.com/cdr/code-server/issues/3425#issuecomment-845326930>

**Comment by capriciousduck** [comment]
Is the linuxserver image built from codercom repo?

**Comment by Roxedus** [comment]
Yes.

**Comment by capriciousduck** [comment]
Oh. How can I set a password in codercom image? I 've check the docs but I don't find anything related to it.

**Comment by Roxedus** [comment]
We do not support the container provided by upstream.
