### ISSUE TITLE
Update the Container

### ISSUE THREAD

**Issue by capriciousduck** [linuxserver/docker-code-server#70]
How to update the code-server from within the container instead of deploying again from a new image?

**Comment by TheSpad** [comment]
We don't support updating the app within the container. To update you need to pull the updated image and recreate.

If you're following our examples and/or using compose to manage your containers this should be very straightforward and will retain all of your settings.

**Comment by capriciousduck** [comment]
What about the packages I install through pip3? Will those, too, be saved after container recreation?

**Comment by Roxedus** [comment]
No, which is why the concept of docker mods and custom startup scripts are very popular to pair with the image

**Comment by capriciousduck** [comment]
How do I create a custom startup script?

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
