### ISSUE TITLE
Disabled extensions are stuck as 'Reload Required'

### ISSUE THREAD

**Issue by Cheezzhead** [linuxserver/docker-code-server#72]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When disabling an extension, it should either immediately stop running, or be stopped during a reload. Running the command "Developer: Show Running Extensions" should not display the disabled extension in the list.

## Current Behavior
Most extensions initially show up as immediately disabled when the 'Disable' button is clicked ('This extension is disabled globally by the user'). Upon reloading the page, workspace, or another workspace or folder, the extension goes back to being enabled, the text 'Please reload Visual Studio Code to disable this extension' displayed, and with a 'Reload Required' button. Pressing the button or refreshing the page changes nothing from this point on. I can re-enable the extension and it will work fine, but that is obviously not what I want.

I have tried this on a fresh image with no data/config folder configured, and all LSIO mods disabled, with the same problem occurring.

## Steps to Reproduce

1. Install and enable any extension (I tried with the MySQL extension)
2. Go to the Extensions tab and disable the extension. Its features are still enabled
3. Reload the page. The extension shows up as enabled with a 'Reload Required' button.

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** DockStarter (which uses the install script from https://get.docker.com/ I believe)

## Command used to create docker container (run/create/compose/screenshot)

```codeserver:
    image: ghcr.io/linuxserver/code-server:version-v3.10.2
    hostname: ${DOCKERHOSTNAME}
    container_name: codeserver
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    networks:
      - default
      - frontendprod
      - backenddev
      - dbdev
      - dbprod
      - api
    restart: unless-stopped  
    volumes:
      # Standard directories
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/codeserver:/config
      - /var/run/docker.sock:/var/run/docker.sock
      environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - SUDO_PASSWORD=###
      - TZ=${TZ}
      - PROXY_DOMAIN=dev.domain.tld
      - DOCKER_MODS=linuxserver/mods:code-server-docker|linuxserver/mods:code-server-flutter|linuxserver/mods:code-server-php|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-npmglobal|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-dotnet
```

## Docker logs

[codeserver.log](https://github.com/linuxserver/docker-code-server/files/6732855/codeserver.log)

**Comment by Cheezzhead** [comment]
Any update on this?

**Comment by franzbischoff** [comment]
This still happening... any update?

**Comment by aptalca** [comment]
This sounds like an upstream issue. Feel free to reopen or report to upstream if still having issues
