### ISSUE TITLE
Somehow it seems that your image does not let dotnet be installed

### ISSUE THREAD

**Issue by Nefcanto** [linuxserver/docker-code-server#77]
I tried your VS Code in the browser, using your [docker-compose.yml](https://hub.docker.com/r/linuxserver/code-server) file, and I loved it.

Then I decided to expand upon your image, install .NET and see how things go.

Thus I created this `Dockerfile`:

```
FROM ghcr.io/linuxserver/code-server

COPY ./dotnet-install.sh dotnet-install.sh

RUN ./dotnet-install.sh --channel 3.1 --verbose

RUN dotnet tool install --global dotnet-ef --version 3.1.12
```

And that `dotnet-install.sh` is the [official installation script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) from Microsoft.

However, when it reaches the last line, it says:

> /bin/sh: 1: dotnet: not found

**Comment by aptalca** [comment]
Why don't you use the mod for it?
https://github.com/linuxserver/docker-mods/tree/code-server-dotnet

**Comment by Nefcanto** [comment]
Really? You have a .NET SDK image and you have named it `mod`. I searched your repository to find .NET and I simply couldn't. Then I scanned all of your repositories and still didn't find anything, because `mod` is not a name that is familiar to a .NET developer.

That's great news. I'll test it right away.

**Comment by Nefcanto** [comment]
It's very difficult to understand.

However, I added this environment variable to my `docker-compose.yml` to test it:

`      - DOCKER_MODS=linuxserver/mods:code-server-dotnet`

And after running `docker-compose up` it's now stuck in this phase:

>Recreating code-server ... done   
Attaching to code-server   
code-server    | [mod-init] Attempting to run Docker Modification Logic

But to be honest, your entire repo is very difficult to understand. I wish you could have a simple code snippet, like an installation script that we could use to add `code-server` to an existing image. Do you have that?

**Comment by Roxedus** [comment]
Docker mods is our way to extend our images.

**Comment by Nefcanto** [comment]
@Roxedus  that's awesome, however, I couldn't simply use it.

I found [this](https://github.com/ptr727/VSCode-Server-DotNetCore) which worked very easily.

My feedback is that you should simplify access to your images. Because your idea is awesome, but I'm one simple case of failure in being able to use them.

Thank you so much for your great work.

**Comment by Roxedus** [comment]
We link to mods in all our readmes. Anything built on top of our images is not getting support by us.

**Comment by aptalca** [comment]
> And after running docker-compose up it's now stuck in this phase:

It's not stuck, it's downloading the mod

> Really? You have a .NET SDK image and you have named it mod

It's not an image and we didn't name it mod. It is a mod (sorry for modification

**Comment by Nefcanto** [comment]
@Roxedus your work is great. However, as a developer who knows little about all those fancy Linux commands, I was searching for something to be used in my `FROM some_image_with_code_server_and_dotnet` line in my `Dockerfile`.

Since you guys are gurus at this, I recommend that you deploy such images.

**Comment by tobbenb** [comment]
Why is that a better way than what we are doing now?
The way it's now, you add an env variable for the mod and recreate the container and it's installed. You just have to be patient and wait for it to finish installing.
It can't be much easier than that.

**Comment by Nefcanto** [comment]
And each time a developer wants to create a container he has to wait a ton of time?
Containers are ephemeral by nature. We destroy them and recreate them frequently.
Containers should be up and running in seconds. Any initialization that takes a long time is a bad decision for a container.

You should embody that in an image, not at the start of the container. Of course, that's a bad decision. There is no arguing that.

Just download any image with over 100M downloads and run a container on top of it and measure the time it takes to load. You'll understand.

That being said, I understand that open-source means spending time free for others. And it's a valuable thing to do, and I'm doing it myself and I'm thankful to you for that. However, it does not mean that others can't help or criticize for improvement.

**Comment by tobbenb** [comment]
Then you are free to do it as you want. You don't have to use our images of you don't like them.

**Comment by Nefcanto** [comment]
That's exactly what I'm doing now. But it's feedback from one person for you. I loved your image, yet I could not use it because of many design flaws in them. Root user support and hardcoded images are two of them. I just say you could support more developers if you only changed a couple of small things.

Anyway, thank you so much for your valuable works and time.
