### ISSUE TITLE
Permission denied while saving a file

### ISSUE THREAD

**Issue by Nefcanto** [linuxserver/docker-code-server#78]
I ran an instance of your image inside a docker and launched VS Code at `localhost:8443`.

However, when I want to save a file, I see this error:

> Failed to save 'TicketController.cs': Unable to write file 'vscode-remote://0.0.0.0:8443/Company/AdminApi/Api/Controllers/TicketController.cs' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Company/AdminApi/Api/Controllers/TicketController.cs')

**Comment by drizuid** [comment]
Please fill out the full template

**Comment by drizuid** [comment]
duplicate of https://github.com/linuxserver/docker-code-server/issues/79
