### ISSUE TITLE
Can we get updated SFTP addon please? Link below

### ISSUE THREAD

**Issue by Rathna-K** [linuxserver/docker-code-server#82]
The current lilmoxo sftp is broken and this is a forked version of the same. Can we please make this available? Currently doesn’t show up in the search. https://github.com/Natizyskunk/vscode-sftp/releases/

**Comment by Roxedus** [comment]
We do not control open-vix nor code-server, this is not the correct repo for this request.

**Comment by Rathna-K** [comment]
Is this the right repo? I couldn’t find any references on which repo this uses. Might be better if you can add it to the description. Thank you.  https://github.com/cdr/code-server

**Comment by Roxedus** [comment]
Yes, that's the repo we link to in the [readme](https://github.com/linuxserver/docker-code-server/blob/master/README.md?plain=1#L41)
