### ISSUE TITLE
Environmental variables not set for current user 

### ISSUE THREAD

**Issue by ot3kcw6c** [linuxserver/docker-code-server#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Environmental variables not set for current user.

------------------------------

## Expected Behavior

The Terminal user in the code-server UI should be able to use the system environmental variables (/etc/environment) from beginning. (Proxy)

## Current Behavior

After starting Code-Server with root uid and guid environment variables, the user needs to be switched to the real root user.

![image](https://user-images.githubusercontent.com/61137563/142901313-b869dcce-f89b-41d0-929f-6f463f13b825.png)
OR
![image](https://user-images.githubusercontent.com/61137563/142900918-0afc78df-6322-43aa-91bc-4092251f8f94.png)

## Steps to Reproduce

1.  Run Code Server with PUID=0 and PGID=0 
2.  Set Proxy environments: echo 'http_proxy=http://www-zproxy.company.com:80\n\
https_proxy=http://www-zproxy.company.com:80\n\
ftp_proxy=ftp://www-zproxy.company.com:80\n\
no_proxy=localhost, 127.0.0.1, company.com, 10.0.0.0/8\n\
soap_use_proxy=on\n' > /etc/environment
3. open in code-server terminal with bash
4. printenv https_proxy (result:empty)

## Environment
**OS:Ubuntu 20.04.3 LTS"**
**CPU architecture:** x64
**How docker service was installed: apt install docker.io**

Own Docker Image based on the official docker repo.

## Command used to create docker container (run/create/compose/screenshot)

  code-server-vstest:
    image: local/code-server:dev
    container_name: code-server-vstest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Vienna
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/code-server/vstest/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
    network_mode: bridge

## Docker logs

,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
setting up sudo access,
setting sudo password using SUDO_PASSWORD env var,
Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully,
setting permissions::configuration,
setting permissions::workspace,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2021-11-22T16:22:20.860Z] info  code-server 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2,
[2021-11-22T16:22:20.861Z] info  Using user-data-dir ~/data,
[2021-11-22T16:22:20.873Z] info  Using config file ~/.config/code-server/config.yaml,
[2021-11-22T16:22:20.873Z] info  HTTP server listening on http://0.0.0.0:8443 ,
[2021-11-22T16:22:20.873Z] info    - Authentication is enabled,
[2021-11-22T16:22:20.873Z] info      - Using password from $PASSWORD,
[2021-11-22T16:22:20.873Z] info    - Not serving HTTPS ,
[2021-11-22T16:38:16.318Z] error Failed to get latest version {"error":"read ETIMEDOUT"},
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    0,
User gid:    0,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
setting up sudo access,
setting sudo password using SUDO_PASSWORD env var,
Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully,
setting permissions::configuration,
setting permissions::workspace,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2021-11-22T16:44:02.361Z] info  code-server 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2,
[2021-11-22T16:44:02.362Z] info  Using user-data-dir ~/data,
[2021-11-22T16:44:02.376Z] info  Using config file ~/.config/code-server/config.yaml,
[2021-11-22T16:44:02.376Z] info  HTTP server listening on http://0.0.0.0:8443 ,
[2021-11-22T16:44:02.376Z] info    - Authentication is enabled,
[2021-11-22T16:44:02.376Z] info      - Using password from $PASSWORD,
[2021-11-22T16:44:02.376Z] info    - Not serving HTTPS ,

**Comment by Roxedus** [comment]
Without taking a real close look, this is probably because the code-server binary is launched before the variables are declared, and thus the terminal not inheriting them.

**Comment by ot3kcw6c** [comment]
running with an other user then PUID=0 (root) it works.
So i don't think the launch order is the problem.

**Comment by ot3kcw6c** [comment]
i temporarily fixed it with docker env variables. (Setting for example https_proxy env variables)
