### ISSUE TITLE
launch.json not working anymore in 3.12.0

### ISSUE THREAD

**Issue by marius-lupu** [linuxserver/docker-code-server#92]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
To be able to debug a Python or a Go application by using the launch.json file.

## Current Behavior
I wanted to debug a Python or a Go application using the Docker Tag "version-v3.12.0" but it doesn't work anymore.
Didn't matter what I put in the launch.json file, the debugging process assumed that there was nothing there and prompted me with the default behavior. I tried to use different launch.json configurations for Python and for Go, even with the ones you can get by using Run > Add Configuration button in VSCode.
The solution is to use Docker Tag "version-v3.11.0"

## Steps to Reproduce
1. Create any basic Python/Go file
2. Create a launch.json file from the VSCode GUI (Run > Add Configuration..)
3. Try to debug the Python/Go file

## Environment
Docker Image used ghcr.io/linuxserver/code-server:version-v3.12.0

**Comment by Roxedus** [comment]
This doesn't sound like a image issue, rather a application issue.

**Comment by marius-lupu** [comment]
Ok, so, it should be handled by this repo https://github.com/cdr/code-server instead?
I found something similar there: https://github.com/cdr/code-server/issues/4221
